version: '3.7'
services:
  db:
    image: postgres
    env_file:
      - .keys.dockenv
  ingestion:
    build: ingestion
    command: >
      sh -c "python3 ingestion/manage.py migrate &&
             python3 ingestion/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=True
    env_file:
      - .keys.dockenv
