version: '3'
services:
  db:
    image: postgres
    env_file:
      - .keys.dockenv
  web:
    build: .
    command: >
      sh -c "python3 stereo8/manage.py migrate &&
             python3 stereo8/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .keys.dockenv
